# Generated by Django 4.0.5 on 2022-06-24 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogram', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duser',
            name='avatar',
            field=models.FileField(blank=True, default='default.png', upload_to='pics'),
        ),
    ]
