# Generated by Django 4.0.5 on 2022-06-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogram', '0004_alter_duser_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duser',
            name='avatar',
            field=models.ImageField(default='default.png', upload_to=''),
        ),
    ]
