# Generated by Django 4.0.5 on 2022-06-26 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogram', '0007_alter_postimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
