# Generated by Django 4.0.5 on 2022-06-26 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogram', '0011_alter_postimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duser',
            name='avatar',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='avatars/'),
        ),
    ]
