# Generated by Django 4.0.5 on 2022-06-30 10:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogram', '0021_alter_likes_post_alter_likes_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='duser',
            name='following',
            field=models.ManyToManyField(blank=True, null=True, related_name='followers', to=settings.AUTH_USER_MODEL),
        ),
    ]
