# Generated by Django 4.0.5 on 2022-07-03 13:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('djangogram', '0024_alter_duser_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tagpost',
            name='post',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tag', to='djangogram.post'),
        ),
        migrations.AlterField(
            model_name='tagpost',
            name='tag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post', to='djangogram.tag'),
        ),
    ]
