# Generated by Django 4.0.5 on 2022-07-29 22:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangogram', '0026_remove_tagpost_post_remove_tagpost_tag_post_tags_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duser',
            name='avatar',
            field=models.ImageField(default='default_hdqd19.png', null=True, upload_to='avatars'),
        ),
    ]
